make powerdown easier to customize

diff --git a/powerdown b/powerdown
--- a/powerdown
+++ b/powerdown
@@ -1,70 +1,205 @@
-#!/usr/bin/env bash
-# powerdown - powersave script
-# please use this with xset dpms, hdparm
+#!/usr/bin/bash
+# powerdown
+
+shopt -s nullglob extglob
+
+# turn on kernel options
+opt() {
+    [[ -f "$1" ]] || return
+    [[ -w "$1" ]] && echo "$2" | tee "$1" &>/dev/null || echo "[powerdown] cannot write $2 to $1"
+}
+
+#turn on kernel options on matched paths
+opts() {
+	for path in $(eval "ls -d $1"); do
+		opt $path $2
+	done
+}
+
+brightness () {
+	for path in $(eval "ls -d $1"); do
+		opt $path/brightness "$(num_scale "$path/max_brightness" $2)"
+	done
+}
+
+# unload kernel module
+unload_mod() {
+    has_mod "$1" || return
+    modprobe -r "$1" || echo "[powerdown] cannot unload module $1"
+}
+
+unload_mod_recursive() {
+	local dep
+	for dep in $(lsmod | awk -v mod="$1" '$1==mod {gsub(",", " ", $4); print $4}'); do
+		unload_mod_recursive "$dep"
+	done
+	unload_mod "$1"
+}
+
+# load kernel module
+load_mod() {
+    has_mod "$1" || return
+    modprobe "$1" || echo "[powerdown] cannot load module $1"
+}
+
+# module exists
+has_mod() {
+    modprobe -nq "$1"
+}
+
+# module loaded
+mod_loaded() {
+    grep -qs "^$1 " /proc/modules
+}
+
+# brightness scale 0 to 5
+# $1 = max file
+# $2 = value
+num_scale() {
+    echo $(($(< "$1") / 5 * $2))
+}
+
+# command
+run() {
+    "$@" &> /dev/null || echo "[powerdown] cannot run $@"
+}
+
+has_bat() {
+	local bat
+	for bat in /sys/class/power_supply/BAT*; do
+		return 0
+	done
+	return 1
+}
+
+# get current power usage
+display_power() {
+    if ! has_bat; then
+        echo "[powerdown] no battery"
+        return
+    fi
+    local bat
+    for bat in /sys/class/power_supply/BAT*; do
+        local watt
+        if [[ -f "$bat/power_now" ]]; then
+            watt="$(bc <<< "scale=3; $(< "$bat/power_now") / 1000000")"
+        else
+            watt="$(bc <<< "scale=3; $(< "$bat/current_now") * $(< "$bat/voltage_now") / 1000000000000")"
+        fi
+        echo "[powerdown] $(basename "$bat") using $watt watts"
+    done
+}
+
+# get readahead
+display_readahead() {
+    echo "- $1 readahead: $(blockdev --getra "$1")"
+}
+
+# dump kernel option content
+dump () {
+    [[ -r "$1" ]] || return
+    echo "- $1: $(< "$1")"
+}
+
+display_module() {
+    has_mod "$1" || return
+    echo -n "- $1 "
+    mod_loaded "$1" && echo "loaded" || echo "not loaded"
+}
+
+display_wireless() {
+    echo "- $1 $(iw dev "$1" get power_save)"
+}
+
+hibernate_offset() {
+    filefrag -v /hibernate | awk 'NR==4 {print $4}' | tr -d .
+}
+
+root_part() {
+    df / | awk 'NR==2 {print $1}'
+}
+
+has_swap_part () {
+    grep -qs swap /etc/fstab
+}
+
+can_suspend_to_disk () {
+    [[ -f /hibernate ]] || has_swap_part
+}
+
+swap_part() {
+    awk '$3=="swap" {print $1; exit}' /etc/fstab
+}
+
+resume_boot_option() {
+    if [[ -f /hibernate ]]; then
+        echo "resume=$(root_part) resume_offset=$(hibernate_offset)"
+    elif has_swap_part; then
+        echo "resume=$(swap_part)"
+    fi
+}
+
+# lock the file until the script finishes
+lock() {
+    local LOCK=/tmp/powerdown.lock
+    if ! mkdir "$LOCK" 2> /dev/null; then
+        echo "Working... $LOCK"
+        exit
+    fi
+    trap "rm -rf $LOCK" EXIT
+}
+
+# $1 = device path
+is_usb_hid() {
+    local subdev
+    for subdev in $1/*:*; do
+        # USB_DEVICE_CLASS 3 = HID
+        [[ "$(< "$subdev/bInterfaceClass")" == 03 ]] && return 0
+    done
+    return 1
+}
+
+usb_powersave() {
+    local usbdev
+    for usbdev in /sys/bus/usb/devices/+([^:]); do
+        is_usb_hid "$usbdev" && opt "$usbdev/power/control" on || opt "$usbdev/power/control" auto
+    done
+}
+unbind_uvcvideo_devices() {
+	for device in /sys/bus/usb/drivers/uvcvideo/*/interface; do
+	       echo $device \
+		       | sed "s|/sys/bus/usb/drivers/uvcvideo/\(.*\)/interface|\1|" \
+		       | tee /sys/bus/usb/drivers/uvcvideo/unbind
+       done
+}
 
 if [[ $EUID != 0 ]]; then
-    echo "[powerdown] must be run as root"
+    echo "[powerdown] must be run as root" 1>&2
     exit 1
 fi
 
-source /usr/lib/powerdown-functions
 lock
 
-# bus
-for i in /sys/bus/*/devices/*/power/control; do opt "$i" auto; done
+state="powerdown"
+if [[ "$1" == "false" ]]; then
+	state="powerup"
+fi
+CONFIG_FILES=$( (ls /etc/powerdown.d ; ls /usr/lib/powerdown/ ) 2> /dev/null \
+	|  grep ".\+.${state}$" \
+	|  sort \
+	|  uniq -u )
 
-# usb autosuspend
-for i in /sys/bus/usb/devices/*/power/autosuspend; do opt "$i" 10; done
-usb_powersave
+readonly CONFIG_FILE
 
-# nmi_watchdog
-opt /proc/sys/kernel/nmi_watchdog 0
+if [ -z "$CONFIG_FILES" ]; then
+	echo "[powerdown] no powerdown config file was found" 1>&2
+	exit 1
+fi
 
-# cpu
-for i in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do opt "$i" powersave; done
-load_mod msr
-run x86_energy_perf_policy powersave
-
-# aspm
-opt /sys/module/pcie_aspm/parameters/policy powersave
-
-# kernel write mode
-opt /proc/sys/vm/laptop_mode 5
-opt /proc/sys/vm/dirty_ratio 90
-opt /proc/sys/vm/dirty_background_ratio 1
-opt /proc/sys/vm/dirty_expire_centisecs 60000
-opt /proc/sys/vm/dirty_writeback_centisecs 60000
-
-# disk
-for i in /sys/class/scsi_host/host*/link_power_management_policy; do opt "$i" min_power; done
-for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run mount -o remount,noatime "$dev"; done
-for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run blockdev --setra 4096 "$dev"; done
-for dev in $(awk '/^\/dev\/sd/ {print $1}' /etc/mtab); do run hdparm -B 1 -S 120 "$dev"; done
-
-# sound card
-opt /sys/module/snd_hda_intel/parameters/power_save 1
-opt /sys/module/snd_hda_intel/parameters/power_save_controller Y
-opt /sys/module/snd_ac97_codec/parameters/power_save 1
-
-# net
-for i in $(iw dev | awk '$1 == "Interface" { print $2 }'); do run iw dev "$i" set power_save on; done
-run ethtool -s eth0 wol d
-
-# screen
-for i in /sys/class/backlight/*; do opt "$i/brightness" "$(num_scale "$i/max_brightness" 1)"; done
-
-# webcam
-unload_mod_recursive videodev
-
-# bluetooth
-unload_mod_recursive bluetooth
-
-# open source ATI
-opt /sys/kernel/debug/vgaswitcheroo/switch OFF
-for i in /sys/class/drm/card*/device/power_method; do opt "$i" profile; done
-for i in /sys/class/drm/card*/device/power_profile; do opt "$i" low; done
-for i in /sys/class/drm/card*/device/power_dpm_state; do opt "$i" battery; done
-
-# i915
-#opt /sys/module/i915/parameters/i915_enable_rc6 1
-exit 0
+for file in $CONFIG_FILES; do
+	if [ -e /etc/powerdown.d/$file ]; then
+		source /etc/powerdown.d/$file
+	else
+		/usr/lib/powerdown/$file
+	fi
+done
